version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:  requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306
  
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build: requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build: requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    expose:
      - 9000

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/machaiba/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/machaiba/data/wordpress